#!/bin/bash/

Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
Color_Off='\033[0m'       # Text Reset

        echo -e "${Blue}***${Red}"##"${Green}#***${Yellow}#${Blue}*#${Yellow}#***#${Yellow}#***${Purple}#**${Cyan}*#***#***#${Blue}##***#${Yellow}*#*#***${Purple}##***#***${Blue}#**${Purple}"

sudo mv ex.zshrc .zshrc
        sleep 1
sudo mv ex.p10k.zsh .p10k.zsh
        sleep 1
sudo cp -r .zshrc $HOME/
sudo cp -r .p10k.zsh $HOME
